name: CI - Tests & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # installiere nur, wenn requirements.txt existiert
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8 || true

    - name: Lint code
      run: |
        # Linter ausführen, bricht aber nicht den Build ab
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || true

    - name: Run tests
      run: |
        pytest || true

    - name: Run tests
      run: |
        pytest
