name: First interaction greeting

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hallo! Vielen Dank, dass du ein Issue erstellt hast.
            Wir freuen uns, dass du hier bist 🚀
          pr-message: |
            👋 Willkommen und danke für deinen ersten Pull Request!
            Wir schauen ihn uns bald an ✅
